### ISSUE TITLE
Never find my file 

### ISSUE THREAD

**Issue by annguye2** [abhinaba-ghosh/any-text#4]
Hi, 

Hope you could help. 
I ran your package, but it never find my file which I wanted to extract the text (even I put the absolute path file into the pramatrer) 
Here is the script that I've used 
function usingAnyText(docFile, rest) {
   
  const reader = require('any-text');

  reader.getText(docFile).then((data) => {
  console.log(data);
});
} 
 Here is the error 

Error: ENOENT: no such file or directory, open './test/data/05-versions-space.pdf'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (/Users/.../projects/test/angular-and-nodejs-data/dist/server.js:201551:25)
    at Object.module.exports.PDFJS (/Users/.../projects/test/angular-and-nodejs-data/dist/server.js:201564:30)
    at __webpack_require__ (/Users/..../projects/test/angular-and-nodejs-data/dist/server.js:27:30)
    at Object.<anonymous> (/Users/...../projects/test/angular-and-nodejs-data/dist/server.js:169624:13)
    at __webpack_require__ (/Users/.../projects/test/angular-and-nodejs-data/dist/server.js:27:30)
    at usingAnyText (/Users/..../projects/test/angular-and-nodejs-data/dist/server.js:273364:18)
    at /Users/..../projects/test/angular-and-nodejs-data/dist/server.js:273298:13
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (/Users/......./projects/test/angular-and-nodejs-data/dist/server.js:135677:31)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-and-nodejs@0.0.0 server: `node local.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-and-nodejs@0.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.      /.npm/_logs/2020-11-30T21_57_02_103Z-debug.log
 
Can you please  help?

**Comment by abhinaba-ghosh** [comment]
Hi @annguye2 Thanks for raising the issue. Can you pass the absolute path of the file. 

```js
`${process.cwd()}/test/data/05-versions-space.pdf`
```
